"use client";

export function TokenUsageDoc() {
  return (
    <div className="prose prose-zinc prose-pre:overflow-x-auto prose-pre:max-w-full">
      <h1>Token Usage Dashboard</h1>
      <p className="lead">
        Track and analyze token consumption across your AI model deployments.
      </p>

      <h2>Overview</h2>
      <p>
        The Token Usage Dashboard provides comprehensive analytics on your AI model token consumption.
        Track prompt and completion tokens across time periods, monitor usage by model and endpoint,
        and export data for billing reconciliation or capacity planning.
      </p>

      <h3>Key Features</h3>
      <ul>
        <li><strong>Usage Tracking</strong> - Monitor prompt, completion, and total token counts</li>
        <li><strong>Time-Based Analysis</strong> - View usage by hour, day, week, or month</li>
        <li><strong>Model Breakdown</strong> - See which models consume the most tokens</li>
        <li><strong>Cost Estimation</strong> - Approximate costs vs pay-per-token APIs</li>
        <li><strong>Export Capabilities</strong> - Download reports as CSV or JSON</li>
        <li><strong>Real-Time Updates</strong> - Live counters during active inference</li>
      </ul>

      <h2>Understanding Token Metrics</h2>

      <table>
        <thead>
          <tr>
            <th>Metric</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Prompt Tokens</strong></td>
            <td>Tokens in your input messages (you send)</td>
          </tr>
          <tr>
            <td><strong>Completion Tokens</strong></td>
            <td>Tokens generated by the model (model sends)</td>
          </tr>
          <tr>
            <td><strong>Total Tokens</strong></td>
            <td>Prompt + Completion combined</td>
          </tr>
          <tr>
            <td><strong>Requests</strong></td>
            <td>Number of API calls made</td>
          </tr>
          <tr>
            <td><strong>Avg Tokens/Request</strong></td>
            <td>Average tokens per inference call</td>
          </tr>
        </tbody>
      </table>

      <h2>Dashboard Sections</h2>

      <h3>Summary Cards</h3>
      <p>Quick overview showing:</p>
      <ul>
        <li>Total tokens used in period</li>
        <li>Prompt vs completion breakdown</li>
        <li>Number of requests</li>
        <li>Comparison to previous period</li>
      </ul>

      <h3>Time Series Chart</h3>
      <p>Interactive chart showing token usage over time:</p>
      <ul>
        <li>Total, prompt, and completion lines</li>
        <li>Hover for exact values</li>
        <li>Zoom and pan controls</li>
        <li>Multiple time granularities</li>
      </ul>

      <h3>Model Breakdown</h3>
      <p>Pie chart showing usage distribution by model:</p>
      <ul>
        <li>Percentage of total tokens per model</li>
        <li>Click to filter by specific model</li>
        <li>Identify high-usage models</li>
      </ul>

      <h2>Time Range Selection</h2>

      <h3>Preset Ranges</h3>
      <ul>
        <li><strong>Today</strong> - Current day, hourly breakdown</li>
        <li><strong>Yesterday</strong> - Previous 24 hours</li>
        <li><strong>Last 7 Days</strong> - Weekly view, daily breakdown</li>
        <li><strong>Last 30 Days</strong> - Monthly view</li>
        <li><strong>This Month</strong> - Current calendar month</li>
        <li><strong>Custom Range</strong> - Select start and end dates</li>
      </ul>

      <h3>Granularity Options</h3>
      <table>
        <thead>
          <tr>
            <th>Range</th>
            <th>Default</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Today</td>
            <td>Hourly</td>
            <td>15min, Hourly</td>
          </tr>
          <tr>
            <td>7 Days</td>
            <td>Daily</td>
            <td>Hourly, Daily</td>
          </tr>
          <tr>
            <td>30 Days</td>
            <td>Daily</td>
            <td>Daily, Weekly</td>
          </tr>
          <tr>
            <td>90 Days</td>
            <td>Weekly</td>
            <td>Daily, Weekly, Monthly</td>
          </tr>
        </tbody>
      </table>

      <h2>Cost Estimation</h2>
      <p>
        While the platform charges by GPU-hour (not tokens), the dashboard provides
        comparative cost estimates to show your savings:
      </p>

      <h3>Comparison Example</h3>
      <pre>
        <code>{`Cost Comparison (if using pay-per-token APIs)
─────────────────────────────────────────────
OpenAI GPT-4 equivalent:    $1,254.38
Claude 3.5 Sonnet equiv:      $876.45
Platform GPU-hour cost:        $32.40
─────────────────────────────────────────────
Savings this period:         $1,221.98 (97.4%)`}</code>
      </pre>

      <h2>Token Counting</h2>

      <h3>How Tokens Are Counted</h3>
      <table>
        <thead>
          <tr>
            <th>Content</th>
            <th>Approximate Tokens</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1 word</td>
            <td>~1.3 tokens</td>
          </tr>
          <tr>
            <td>1 sentence</td>
            <td>~15-20 tokens</td>
          </tr>
          <tr>
            <td>1 paragraph</td>
            <td>~100-150 tokens</td>
          </tr>
          <tr>
            <td>1 page (500 words)</td>
            <td>~650 tokens</td>
          </tr>
          <tr>
            <td>Code (1 function)</td>
            <td>~50-200 tokens</td>
          </tr>
        </tbody>
      </table>

      <h3>Estimating Before Requests</h3>
      <pre>
        <code>{`# Python example using tiktoken
import tiktoken

def estimate_tokens(text, model="gpt-4"):
    encoding = tiktoken.encoding_for_model(model)
    return len(encoding.encode(text))

# For LLaMA-style models, use cl100k_base
encoding = tiktoken.get_encoding("cl100k_base")
tokens = len(encoding.encode("Your prompt here"))`}</code>
      </pre>

      <h2>Data Export</h2>

      <h3>Export Formats</h3>
      <ul>
        <li><strong>CSV</strong> - Spreadsheet-compatible</li>
        <li><strong>JSON</strong> - API/programmatic use</li>
      </ul>

      <h3>CSV Format</h3>
      <pre>
        <code>{`timestamp,model,prompt_tokens,completion_tokens,total_tokens,requests
2025-01-17T00:00:00Z,meta-llama/Llama-3.1-70B-Instruct,45678,98765,144443,234
2025-01-17T01:00:00Z,meta-llama/Llama-3.1-70B-Instruct,52341,112456,164797,267`}</code>
      </pre>

      <h3>JSON Format</h3>
      <pre>
        <code>{`{
  "period": {
    "start": "2025-01-17T00:00:00Z",
    "end": "2025-01-17T23:59:59Z"
  },
  "summary": {
    "total_tokens": 12543890,
    "prompt_tokens": 4231456,
    "completion_tokens": 8312434,
    "requests": 45678
  },
  "by_model": [
    {
      "model": "meta-llama/Llama-3.1-70B-Instruct",
      "tokens": 5644750,
      "percentage": 45.0
    }
  ]
}`}</code>
      </pre>

      <h2>Usage Alerts</h2>
      <p>Set notifications for usage thresholds:</p>
      <table>
        <thead>
          <tr>
            <th>Alert Type</th>
            <th>Example</th>
            <th>Use Case</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Daily Limit</td>
            <td>&gt; 1M tokens/day</td>
            <td>Budget control</td>
          </tr>
          <tr>
            <td>Hourly Spike</td>
            <td>&gt; 200% of average</td>
            <td>Detect anomalies</td>
          </tr>
          <tr>
            <td>Low Usage</td>
            <td>&lt; 10K tokens/day</td>
            <td>Monitor for issues</td>
          </tr>
          <tr>
            <td>Per-Model</td>
            <td>Model X &gt; 500K/day</td>
            <td>Track specific workloads</td>
          </tr>
        </tbody>
      </table>

      <h2>Best Practices</h2>

      <h3>Reducing Token Usage</h3>
      <ol>
        <li><strong>Concise Prompts</strong> - Remove unnecessary words</li>
        <li><strong>Reuse System Prompts</strong> - Cache across conversations</li>
        <li><strong>Implement Caching</strong> - Cache common responses</li>
        <li><strong>Summarize History</strong> - Compress conversation history</li>
        <li><strong>Set max_tokens</strong> - Limit response length appropriately</li>
      </ol>

      <h3>Monitoring Efficiency</h3>
      <table>
        <thead>
          <tr>
            <th>Metric</th>
            <th>Target</th>
            <th>Meaning</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Completion/Prompt Ratio</td>
            <td>1.5-3x</td>
            <td>Normal response expansion</td>
          </tr>
          <tr>
            <td>Avg Tokens/Request</td>
            <td>&lt; 1000</td>
            <td>Efficient requests</td>
          </tr>
          <tr>
            <td>Empty Responses</td>
            <td>&lt; 1%</td>
            <td>Healthy generation</td>
          </tr>
        </tbody>
      </table>

      <h2>API Reference</h2>

      <h3>Get Usage Summary</h3>
      <pre>
        <code>{`GET /api/usage/summary?from=2025-01-01&to=2025-01-17
Authorization: Bearer YOUR_API_KEY`}</code>
      </pre>

      <h3>Get Hourly Breakdown</h3>
      <pre>
        <code>{`GET /api/usage/hourly?date=2025-01-17
Authorization: Bearer YOUR_API_KEY`}</code>
      </pre>

      <h3>Export Usage Data</h3>
      <pre>
        <code>{`GET /api/usage/export?format=csv&from=2025-01-01&to=2025-01-17
Authorization: Bearer YOUR_API_KEY`}</code>
      </pre>

      <h2>Need Help?</h2>
      <p>
        Contact us at{" "}
        our support team via the <strong>Support</strong> tab
      </p>
    </div>
  );
}
